// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("DAL.Entities.DayIntake", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(127); ;

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasMaxLength(127); ;

                    b.Property<double>("DayCalories")
                        .HasColumnType("double")
                        .HasMaxLength(127); ;

                    b.Property<int?>("PointerId")
                        .HasColumnType("int")
                        .HasMaxLength(127); ;

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(127); ;

                    b.HasKey("DayId");

                    b.HasIndex("UserId");

                    b.ToTable("DayIntake");
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(127); ;

                    b.Property<double>("Calories")
                        .HasColumnType("double")
                        .HasMaxLength(127); ;

                    b.Property<double>("Carbs")
                        .HasColumnType("double")
                        .HasMaxLength(127); ;

                    b.Property<double>("Fat")
                        .HasColumnType("double")
                        .HasMaxLength(127); ;

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasMaxLength(127); ;

                    b.Property<double>("Protein")
                        .HasColumnType("double")
                        .HasMaxLength(127); ;

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(127); ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(127); ;

                    b.Property<double>("Callories")
                        .HasColumnType("double")
                        .HasMaxLength(127); ;

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.Entities.DayIntake", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Statistics")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Favourite")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("Favourite");

                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}


/*
 * 
 * #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("FoodyAPI.Models.DayIntake", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DayCalories")
                        .HasColumnType("double");

                    b.Property<int?>("PointerId")
                        .HasColumnType("int");

                    b.Property<string>("userID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("DayId");

                    b.HasIndex("userID");

                    b.ToTable("DayIntake");
                });

            modelBuilder.Entity("FoodyAPI.Models.Product", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Calories")
                        .HasColumnType("double");

                    b.Property<double>("Carbs")
                        .HasColumnType("double");

                    b.Property<double>("Fat")
                        .HasColumnType("double");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Protein")
                        .HasColumnType("double");

                    b.Property<string>("UserID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ProdId");

                    b.HasIndex("UserID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FoodyAPI.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("callories")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodyAPI.Models.DayIntake", b =>
                {
                    b.HasOne("FoodyAPI.Models.User", "user")
                        .WithMany("Statistics")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("user");
                });

            modelBuilder.Entity("FoodyAPI.Models.Product", b =>
                {
                    b.HasOne("FoodyAPI.Models.User", "User")
                        .WithMany("Favourite")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodyAPI.Models.User", b =>
                {
                    b.Navigation("Favourite");

                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}